# CMake toolchain for MSYS2 UCRT64
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(UCRT64 "C:/msys64/ucrt64")
set(CMAKE_C_COMPILER   "${UCRT64}/bin/gcc.exe")
set(CMAKE_CXX_COMPILER "${UCRT64}/bin/g++.exe")
set(CMAKE_RC_COMPILER  "${UCRT64}/bin/windres.exe")

set(CMAKE_FIND_ROOT_PATH "${UCRT64}")
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
